
# use along with the CN group
fuck-gfw=true

#log-file="dnsrelay.log"

geoip-mmdb-file="GeoLite2-Country.mmdb"

# Default action is send all queries to DEFAULT groups
default-group = ["CN","FG"]

[Cache]
backend = "memory"
expire = 600  # default expire time 10 minutes
maxcount = 500

[IPFilter]
ip=[
   "64.111.96.204"
   ]

net=[
    "32.32.32.0/24"
    ]

#
# The "CN" group is special that will enable geoip filtering strategy
# The "REJECT" group is special that will block the domain
#
[DNSGroup]
CN=["192.168.1.1", "114.114.114.114", "223.6.6.6:53", "223.5.5.5"]
FG=["8.8.8.8", "8.8.4.4"]

[[DomainRule]]
# MATCH/SUFFIX/KEYWORD
match-type="MATCH"
domain-group="CN"
value=[
    "order.mi.com",
    "baidu.com",
    ]


[[DomainRule]]
# match/suffix/keyword
match-type="SUFFIX"
domain-group="REJECT"
value=["umeng.com"]


[[Host]]
name="example.com"
ip=["1.1.1.1"]

[[Host]]
name="aa.co"
ip=["3.3.3.3"]