
# use along with the CN group
fuck-gfw=true
addr=""
port=5356
geoip-mmdb-file="GeoLite2-Country.mmdb"

# Default action is send all queries to DEFAULT groups
default-group = ["CN","FG"]

[Log]
# log-file="dnsrelay.log"
log-level="DEBUG"

[Cache]
backend = "memory"
expire = 3600
maxcount = 500

[IPFilter]
ip=[
   "64.111.96.204"
   ]

net=[
    "32.32.32.0/24"
    ]

#
# The "CN" group is special that will enable geoip filtering strategy
# The "REJECT" group is special that will block the domain
#
[DNSGroup]
CN=["192.168.1.1", "114.114.114.114", "223.6.6.6:53", "223.5.5.5"]
FG=["8.8.8.8", "8.8.4.4"]

[[DomainRule]]
# MATCH/SUFFIX/KEYWORD
match-type="MATCH"
domain-group="CN"
value=[
    "order.mi.com",
    "baidu.com",
    ]


[[DomainRule]]
match-type="SUFFIX"
domain-group="REJECT"
value=["umeng.com"]


[[Host]]
name="example.com"
ip=["93.184.216.34"]

[[Host]]
name="ip.com"
ip=["64.111.96.203"]